os: linux
dist: focal
arch: amd64
language: ruby

services:
  - docker
script:
  - docker-compose run --no-deps web rails new . --force --database=postgresql
  - sudo chown -R $USER:$USER .
  - docker-compose build
  - docker-compose up
  - docker network inspect bridge
  - ip addr
  - ip addr show eth0
  - ip addr show ens4
